config/routes.rb
Rails.application.routes.draw do

  get 'users/login_page'
  put 'users/allow_login'
  get 'users/logout'
  resources :users
  resources :appointments
  resources :pet_records

   root 'users#login_page'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	validates :visit_date , :presence => true
	validates :pet_name , :presence => true
	validates :customer_email , :presence => true
	validates :reason_of_visit , :presence => true
	belongs_to :user
	has_many :pet_records
	validate :validate_date?
    def validate_date?
      if visit_date < Date.today
         errors.add(:visit_date, 'Invalid date') 
      end 
    end
end

app/models/pet_record.rb
class PetRecord < ActiveRecord::Base
    validates :visit_date, :presence => true, :length=> {:maximum=>35}
    validates :breed, :presence => true, :length=> {:maximum=>35}
    validates :age , :presence=> true
    validates :weight, :presence=> true
    validates :date_0f_last_visit, :presence=> true

	belongs_to :appointment
end

app/models/user.rb
class User < ActiveRecord::Base

   #to validate the fields
   validates :name, :presence => true, :length=> {:maximum=>35}
   validates :email, :presence => true, :uniqueness => true
   validates :password, :presence => true, :length => {:maximum  => 8, :minimum=> 4}
   validates :zip, :presence => true, :length=> {:minimum=>5}
   validates :total_practice, :presence => true, :length=> {:minimum=>1, :maximum=>100}
   has_many :pet_records
   has_many :appointments
   # use this code to encrypt the code
   before_create do |user|
      self.password =   Digest::MD5.hexdigest(password)
      self.confirm_password =   Digest::MD5.hexdigest(confirm_password)
   end

   after_validation do |user|
     if %w(abuse1 abuse2 abuse3 abuse).include?(name)
         self.name = "Unknown"
     end
   end
  
   def self.authenticate(email, password)
     @user=User.where(:email=> email, :password=>Digest::MD5.hexdigest(password))
     if !@user.blank?
       @user.first
     else
      nil
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :validate_session
  def validate_session
    if session[:user_id].blank?
       redirect_to root_path
    end
  end
  def current_user
    User.find session[:user_id]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    if current_user.position == "receptionist"
      @appointment= Appointment.all 
    else 
  	  @appointment= Appointment.where(:user_id=>current_user.id)
    end
  end

  def new
  	@appointment= Appointment.new
  end
  def create
    byebug
     @appointment= Appointment.new(appointment_params)
     if @appointment.save
        redirect_to :action=>"index"
    else
    	render "new"
     end
  end
private
  def appointment_params
     params.require(:appointment).permit!	 
  end

end

app/controllers/pet_records_controller.rb
class PetRecordsController < ApplicationController
  def index
     @appointment=Appointment.find_by_customer_email current_user.email
     @pet_record=PetRecord.where(:appointment_id=> @appointment.id)
  end
  def new
  	@pet_record=PetRecord.new
  end
  def create
    
  	@pet_record=PetRecord.new(pet_record_params.merge!(:user_id=>current_user.id))
  	if @pet_record.save
       @pet_records.update_columns(:appointment_id=> params["appointmen_id"])
       redirect_to appointments_path
    else
        render "new"	 
  	end
  end
  private
  def pet_record_params
    params.require(:pet_record).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :validate_session, only: [:new, :create, :login_page ,:allow_login]
  def index
   @user=User.all
  end

  def new
    @user=User.new
  end
  def create
   @user=User.new(user_params)
   if @user.save
     session[:user_id] = @user.id
     redirect_to :action=> "index"
     flash[:notice] = "Successfully Created :)"
   else
     render "new" 
   end
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    
   @user=User.find(params[:id])
   #@user.update_attributes(user_params)
   @user.update_columns(user_params)
   if @user
     redirect_to :action=> "index"
     flash[:notice] = "Successfully Updated :)"
   else
     render "new"
   end
  
end
  def show
   @user=User.find(params[:id])
  end
  def destroy
    @user=User.find(params[:id])
    @user.delete
    redirect_to :action=> "index"
  end
  def login_page
    @user= User.new
  end
  def allow_login
    @user = User.authenticate(params[:user][:email], params[:user][:password])
    if @user and (@user.position == "Head" or @user.position == "Helper")
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      elsif @user and @user.position == "receptionist"
        session[:user_id] = @user.id
        redirect_to :controller=>"appointments", :action => "new"
         elsif @user and @user.position.blank?
        session[:user_id] = @user.id
        redirect_to :controller=>"pet_records", :action => "index"
    else
       redirect_to  root_path
    end
  end
 
  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
  private 
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
       User.find session[:user_id]
	end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pet_records_helper.rb
module PetRecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.erb
<table>
	<tr>
		
		<td>Pet</td>
		<td>Date of visit</td>
		<td>Customer</td>
		<td>Reminder of Appointment</td>
		<td>Reason for Visit</td>

	</tr>
	<% @appointment.each do |a|%>
	<td><%= link_to a.pet_name, new_pet_record_path(:appointmen_id=>a.id)%></td>
	<td><%= a.visit_date%></td>
	<td><%= a.customer_email%></td>
	<td><%= a.reminder_date%></td>
	<td><%= a.reason_of_visit%></td>
	<%end%>
	<tr>
	</tr>
</table>
<%= link_to "New Appointment" , new_appointment_path if current_user.position == "receptionist"%>

app/views/appointments/new.html.erb
<%= form_for @appointment do |form| %>
<%= form.label :visit_date%>
<%= form.date_select :visit_date%>
<%= form.label :pet_name, "Pet"%>
<%= form.text_field :pet_name%>
<%= form.label :customer_email, "Customer Email"%>
<%= form.text_field :customer_email%>
<%= form.label :reminder_date, "Requires Reminder of Appointment"%>
<%= form.check_box :reminder_date, {}, "true", "false"%>
<%= form.label :reason_of_visit, "Reason for Visit"%>
<%= form.text_field :reason_of_visit%>
<%= form.select :user_id, User.where("position is 'Head' or position is 'Helper'").collect{|a|[a.name,a.id]}%>
<%= form.submit%>

<%end%>

<%= link_to "See Appointment" , appointments_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   <% if !session[:user_id].blank? %>
     <%= link_to "Logout", :controller=>"users", :action=>"logout"%>
   <%end%>

    <%= yield %>
    <% flash.each do |key, value|%>
     <%= value%>
    <%end%>
  </body>
</html>

app/views/pet_records/index.html.erb
<table>
	<tr>
		
		<td>Pet Name</td>
		<td>Date of Next Appointment</td>
		<td>Reason for Visit</td>

	</tr>
	<% @pet_record.each do |a|%>
	<td><%= a.pet_name%></td>
	<td><%= a.date_0f_last_visit%></td>
	<td><%= a.reminder_date%></td>
	<td><%= @appointment.reason_of_visit%></td>
	<%end%>
	<tr>
	</tr>
</table>

app/views/pet_records/new.html.erb
<%= form_for([@pet_record], :url=> {:controller=>"pet_records",:action=>"create",:appointment_id=> params["appointmen_id"]}) do |form| %>
<%= form.label :pet_name%>
<%= form.text_field :pet_name%>
<%= form.label :type_of_pet%>
<%= form.select :type_of_pet, ["dog", "cat", "bird"]%>
<%= form.label :breed%>
<%= form.text_field :breed%>
<%= form.label :age%>
<%= form.text_field :age%>
<%= form.label :weight%>
<%= form.text_field :weight%>
<%= form.label :date_0f_last_visit%>
<%= form.date_select :date_0f_last_visit%>
<%= form.submit%>

<%end%>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <% @user.errors.messages.each  do |msg|%>
    <%= msg%>
  <%end%>
<%end%>


<%= form_for @user do |f| %>
<table>
  <tr>
    <td><%= f.label :name%></td>
    <td><%= f.text_field :name%></td>
</tr>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.text_field :email%></td>
  </tr>
  <tr>
    <td><%= f.label :contact_no%></td>
    <td><%= f.text_field :contact_no%></td>
  </tr>
  <tr>
    <td><%= f.submit "Edit"%></td>
  </tr>
</table>
<%end%>
<%= link_to "Go Back", :controller=>"users", :action=>"index"%>
~                                                                          

app/views/users/index.html.erb
<table>
<tr>
<th>Name</th>
<th>Address</th>
<th>City</th>
<th>State</th>
<th>Zip</th>
<th>Graduated from</th>
<th>Years in practice</th>
</tr>
<% @user.each do |f|%>
<tr>
	<% if f.position == "Helper" %>
<td><%= f.name %></td>
<td><%= f.address %></td>
<td><%= f.city %></td>
<td><%= f.state %></td>
<td><%= f.zip %></td>
<td><%= f.last_graduated_from %></td>
<td><%= f.total_practice %></td>
<%end%>
</tr>
<%end%>

<% if (User.find session[:user_id]).position== "Head"%>
<tr>
<td><%= link_to "see appoinments" , appointments_path%></td>
</tr>
<%end%>
</table>

app/views/users/login_page.html.erb
<div class = "backg">
<% if @user.errors.any? %>
  <% @user.errors.messages.each  do |msg|%>
    <%= msg%>
  <%end%>
<%end%>


<%= form_for([@user], :url=> {:controller=>"users", :action=>"allow_login"} , :method=> "put") do |f| %>
<table>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.text_field :email%></td>
  </tr>
  <tr>
    <td><%= f.label :password%></td>
    <td><%= f.password_field :password%></td>
  </tr>
  <tr>
    <td><%= f.submit "Login"%></td>
    <td><%= link_to "Sign Up", :controllers=>"users" ,:action=>"new"%></td>
  </tr>
</table>
<%end%>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <% @user.errors.messages.each  do |msg|%>
    <%= msg%>
  <%end%>
<%end%>


<%= form_for @user do |f| %>
<table>
  <tr>
    <td><%= f.label :name%></td>
    <td><%= f.text_field :name%></td>
</tr>
  <tr>
    <td><%= f.label :email%></td>
    <td><%= f.text_field :email%></td>
  </tr>
  <tr>
    <td><%= f.label :password%></td>
    <td><%= f.password_field :password%></td>
  </tr>
  <tr>
    <td><%= f.label :confirm_password%></td>
    <td><%= f.password_field :confirm_password%></td>
  </tr>
  <tr>
    <td><%= f.label :address%></td>
    <td><%= f.text_field :address%></td>
  </tr>
    <tr>
    <td><%= f.label :city%></td>
    <td><%= f.text_field :city%></td>
  </tr>
    <tr>
    <td><%= f.label :state%></td>
    <td><%= f.text_field :state%></td>
  </tr>
    <tr>
    <td><%= f.label :zip%></td>
    <td><%= f.text_field :zip%></td>
  </tr>
    <tr>
    <td><%= f.label :last_graduated_from%></td>
    <td><%= f.text_field :last_graduated_from%></td>
  </tr>
    <tr>
    <td><%= f.label :total_practice%></td>
    <td><%= f.text_field :total_practice%></td>
  </tr>
  <tr>
    <td><%= f.submit "Register"%></td>
  </tr>
</table>
<%end%>
<%= link_to "Go Back", :controller=>"users", :action=>"index"%>

app/views/users/show.html.erb
<table>
<tr>
<th>Name</th>
<th>Address</th>
<th>City</th>
<th>State</th>
<th>Zip</th>
<th>Graduated from</th>
<th>Years in practice</th>
</tr>
<tr>
<td><%= @user.name %></td>
<td><%= @user.address %></td>
<td><%= @user.city %></td>
<td><%= @user.state %></td>
<td><%= @user.zip %></td>
<td><%= @user.last_graduated_from %></td>
<td><%= @user.total_practice %></td>
</tr>


<% if (User.find session[:user_id]).position== "Head"%>
<tr>
<td><%= link_to "additional veterinary", :controller=>"users", :action=>"index" %><td>
</tr>
	<tr>
<td><%= link_to "see appoinments" , appointments_path%><td>
</tr>
<%else%>
<%= link_to "see appoinments" , appointments_path%>
<%end%>
</table>